# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint1', models.CharField(max_length=1000)),
                ('hint2', models.CharField(max_length=1000)),
                ('hint3', models.CharField(max_length=1000)),
                ('hint4', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='hint',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question_bank'),
        ),
    ]
