# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_bank_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='is_correct',
            field=models.IntegerField(max_length=10),
        ),
    ]
