# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20170425_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='question',
            field=models.FileField(upload_to=''),
        ),
    ]
